[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "aiogram>=3.17.0",
    "embedchain>=0.1.126",
    "flask>=3.1.0",
    "werkzeug>=3.1.3",
]
